### ISSUE TITLE
Hi Sebastiz

### ISSUE THREAD

**Issue by lasindu-demel** [sebastiz/PhysiMineR#1]
Can you please let me know where the data resources I can find?

Sorry to submit this as an issue. I had no choices.

Thank you.

**Comment by sebastiz** [comment]
Hi @lasindu-demel . I dont have any synthetic data associated with this project at the moment but it is planned for the future.

**Comment by lasindu-demel** [comment]
Ok cool.  I'm currently working on a research project on Esophageal Cancer. @sebastiz Please let me know if there are any updates.

Thank you,

**Comment by sebastiz** [comment]
Ok great. If you are working on oesophageal cancer and need to clean endoscopy and pathology reports then you should check out EndoMineR (https://github.com/ropensci/EndoMineR). This does have synthetic data and is well documented
